apiVersion: apps/v1
kind: Deployment
metadata:
   name: ecom-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecom
  template:
    metadata:  
     labels:   
       app: ecom      
    spec: 
     containers:  
       - name: ecom-container # container name - optional   
         image: chetansingh673/multibranch-flask-app:build-2
         ports: 
           - containerPort: 5000
          
